---
abstract: 'just mucking about with dist stuff'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Playpen
no_index:
  package:
    - Acme::Playpen::Utilities
requires:
  strict: 0
  warnings: 0
version: 0.01
